# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions


from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def GenerateRecommendations(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.RoleRecommendations:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GenerateRecommendations", llm_response=llm_response, mode="request")
        return typing.cast(types.RoleRecommendations, __result__)

    def ScoreRole(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.RoleAnalysis:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ScoreRole", llm_response=llm_response, mode="request")
        return typing.cast(types.RoleAnalysis, __result__)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def GenerateRecommendations(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.RoleRecommendations:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GenerateRecommendations", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.RoleRecommendations, __result__)

    def ScoreRole(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.RoleAnalysis:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ScoreRole", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.RoleAnalysis, __result__)

    