# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (7)
# #########################################################################

class AISScores(BaseModel):
    cognitive_routine_level: typing.Optional["VariableScore"] = Field(default=None, description='Degree to which cognitive tasks follow predictable, rule-based patterns. High = highly routine.')
    data_dependency: typing.Optional["VariableScore"] = Field(default=None, description='Extent to which the role works with structured, machine-readable data. High = heavily data-dependent.')
    process_repeatability: typing.Optional["VariableScore"] = Field(default=None, description='Degree to which processes are standardised, repeatable, high-volume. High = highly standardised.')
    social_perception: typing.Optional["VariableScore"] = Field(default=None, description='Degree to which role requires reading social cues, empathy, negotiation. High = high social requirement.')
    physical_complexity: typing.Optional["VariableScore"] = Field(default=None, description='Degree to which role requires physical presence, dexterity. High = high physical requirement.')
    regulatory_accountability: typing.Optional["VariableScore"] = Field(default=None, description='Degree to which role carries personal regulatory/legal/fiduciary accountability. High = high accountability.')

class APSScores(BaseModel):
    knowledge_processing: typing.Optional["VariableScore"] = Field(default=None, description='Volume and complexity of information the role must synthesise or produce. High = heavy knowledge work.')
    output_sensitivity: typing.Optional["VariableScore"] = Field(default=None, description='Degree to which outputs benefit from higher volume or improved quality. High = significant gains from AI.')
    decision_support: typing.Optional["VariableScore"] = Field(default=None, description='Extent to which role makes/supports complex decisions benefiting from data analysis. High = heavy decision needs.')
    repetitive_cognitive: typing.Optional["VariableScore"] = Field(default=None, description='Amount of repetitive analytical/cognitive tasks within an expert-level role. High = lots of repetitive expert work.')
    communication_volume: typing.Optional["VariableScore"] = Field(default=None, description='Volume of communication, coordination, collaboration the role manages. High = heavy communication load.')

class Recommendation(BaseModel):
    title: typing.Optional[str] = Field(default=None, description='Short actionable title, e.g. \'Deploy AI document drafting tool\'')
    description: typing.Optional[str] = Field(default=None, description='2-3 sentences explaining what to do, why, and expected impact')
    priority: typing.Optional[types.RecommendationPriority] = None
    category: typing.Optional[types.RecommendationCategory] = None
    affected_tasks: typing.List[str] = Field(description='Which tasks from the role analysis this recommendation addresses')

class RoleAnalysis(BaseModel):
    tasks: typing.List["TaskItem"] = Field(description='5-15 discrete tasks extracted from the role description, each categorised')
    ais: typing.Optional["AISScores"] = None
    aps: typing.Optional["APSScores"] = None

class RoleRecommendations(BaseModel):
    summary: typing.Optional[str] = Field(default=None, description='2-3 sentence executive summary of the strategic recommendation for this role')
    recommendations: typing.List["Recommendation"] = Field(description='3-6 specific, actionable recommendations ordered by priority')
    estimated_productivity_gain: typing.Optional[str] = Field(default=None, description='Qualitative estimate: e.g. \'20-30% time savings on analytical tasks\'')
    transition_risk: typing.Optional[str] = Field(default=None, description='Key risk if this role is not addressed: e.g. \'Competitor advantage if manual processes persist\'')

class TaskItem(BaseModel):
    description: typing.Optional[str] = Field(default=None, description='A discrete task extracted from the role description')
    category: typing.Optional[types.TaskCategory] = Field(default=None, description='Whether this task is automatable, augmentable, or human-essential')

class VariableScore(BaseModel):
    score: typing.Optional[int] = Field(default=None, description='Score from 0-100')
    justification: typing.Optional[str] = Field(default=None, description='2-3 sentences citing specific tasks from the role')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
