# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.AISScores": types.AISScores,
    "stream_types.AISScores": stream_types.AISScores,

    "types.APSScores": types.APSScores,
    "stream_types.APSScores": stream_types.APSScores,

    "types.Recommendation": types.Recommendation,
    "stream_types.Recommendation": stream_types.Recommendation,

    "types.RoleAnalysis": types.RoleAnalysis,
    "stream_types.RoleAnalysis": stream_types.RoleAnalysis,

    "types.RoleRecommendations": types.RoleRecommendations,
    "stream_types.RoleRecommendations": stream_types.RoleRecommendations,

    "types.TaskItem": types.TaskItem,
    "stream_types.TaskItem": stream_types.TaskItem,

    "types.VariableScore": types.VariableScore,
    "stream_types.VariableScore": stream_types.VariableScore,


    "types.RecommendationCategory": types.RecommendationCategory,

    "types.RecommendationPriority": types.RecommendationPriority,

    "types.TaskCategory": types.TaskCategory,

}