# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (3)
# #########################################################################

class RecommendationCategory(str, Enum):
    Automate = "Automate"
    Augment = "Augment"
    Upskill = "Upskill"
    Restructure = "Restructure"
    Monitor = "Monitor"

class RecommendationPriority(str, Enum):
    High = "High"
    Medium = "Medium"
    Low = "Low"

class TaskCategory(str, Enum):
    Automatable = "Automatable"
    Augmentable = "Augmentable"
    HumanEssential = "HumanEssential"

# #########################################################################
# Generated classes (7)
# #########################################################################

class AISScores(BaseModel):
    cognitive_routine_level: "VariableScore" = Field(description='Degree to which cognitive tasks follow predictable, rule-based patterns. High = highly routine.')
    data_dependency: "VariableScore" = Field(description='Extent to which the role works with structured, machine-readable data. High = heavily data-dependent.')
    process_repeatability: "VariableScore" = Field(description='Degree to which processes are standardised, repeatable, high-volume. High = highly standardised.')
    social_perception: "VariableScore" = Field(description='Degree to which role requires reading social cues, empathy, negotiation. High = high social requirement.')
    physical_complexity: "VariableScore" = Field(description='Degree to which role requires physical presence, dexterity. High = high physical requirement.')
    regulatory_accountability: "VariableScore" = Field(description='Degree to which role carries personal regulatory/legal/fiduciary accountability. High = high accountability.')

class APSScores(BaseModel):
    knowledge_processing: "VariableScore" = Field(description='Volume and complexity of information the role must synthesise or produce. High = heavy knowledge work.')
    output_sensitivity: "VariableScore" = Field(description='Degree to which outputs benefit from higher volume or improved quality. High = significant gains from AI.')
    decision_support: "VariableScore" = Field(description='Extent to which role makes/supports complex decisions benefiting from data analysis. High = heavy decision needs.')
    repetitive_cognitive: "VariableScore" = Field(description='Amount of repetitive analytical/cognitive tasks within an expert-level role. High = lots of repetitive expert work.')
    communication_volume: "VariableScore" = Field(description='Volume of communication, coordination, collaboration the role manages. High = heavy communication load.')

class Recommendation(BaseModel):
    title: str = Field(description='Short actionable title, e.g. \'Deploy AI document drafting tool\'')
    description: str = Field(description='2-3 sentences explaining what to do, why, and expected impact')
    priority: RecommendationPriority
    category: RecommendationCategory
    affected_tasks: typing.List[str] = Field(description='Which tasks from the role analysis this recommendation addresses')

class RoleAnalysis(BaseModel):
    tasks: typing.List["TaskItem"] = Field(description='5-15 discrete tasks extracted from the role description, each categorised')
    ais: "AISScores"
    aps: "APSScores"

class RoleRecommendations(BaseModel):
    summary: str = Field(description='2-3 sentence executive summary of the strategic recommendation for this role')
    recommendations: typing.List["Recommendation"] = Field(description='3-6 specific, actionable recommendations ordered by priority')
    estimated_productivity_gain: str = Field(description='Qualitative estimate: e.g. \'20-30% time savings on analytical tasks\'')
    transition_risk: str = Field(description='Key risk if this role is not addressed: e.g. \'Competitor advantage if manual processes persist\'')

class TaskItem(BaseModel):
    description: str = Field(description='A discrete task extracted from the role description')
    category: TaskCategory = Field(description='Whether this task is automatable, augmentable, or human-essential')

class VariableScore(BaseModel):
    score: int = Field(description='Score from 0-100')
    justification: str = Field(description='2-3 sentences citing specific tasks from the role')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
